import type {
    Driver,
    MemberProfile,
    Ride,
    ServiceOption,
} from "@/lib/types";

export const member: MemberProfile = {
    id: "member-driver-1",
    name: "Michael Johnson",
    initials: "MJ",
    memberSince: "2021",
    pickupAddress: "150 Main St, Winnipeg",
    defaultPassengers: "1 Adult",
    phoneNumber: "(204) 555-0199",
    hasCar: true,
    isApprovedDriver: true,
    driverId: "driver-1",
};

export const serviceOptions: ServiceOption[] = [
    {
        id: "sunday",
        title: "Sunday",
        icon: "☀️",
        time: "10:00 AM",
        date: "Sept 30, 2025",
    },
    {
        id: "wednesday",
        title: "Wednesday",
        icon: "🌙",
        time: "7:00 PM",
        date: "Oct 02, 2025",
    },
];

export const drivers: Driver[] = [
    {
        id: "driver-1",
        name: "Michael Johnson",
        initials: "MJ",
        rating: 4.9,
        totalRides: 127,
        vehicle: "Toyota Camry · Blue",
        phoneNumber: "(204) 555-0199",
        address: "150 Main St, Winnipeg",
        distanceKm: 1.2,
        hasVehicle: true,
        isAvailable: true,
        assignedRideId: "ride-1",
    },
    {
        id: "driver-2",
        name: "Sarah Williams",
        initials: "SW",
        rating: 4.8,
        totalRides: 95,
        vehicle: "Honda CR-V · White",
        phoneNumber: "(204) 555-0188",
        address: "280 Main St, Winnipeg",
        distanceKm: 2.4,
        hasVehicle: true,
        isAvailable: true,
        assignedRideId: null,
    },
    {
        id: "driver-3",
        name: "David Brown",
        initials: "DB",
        rating: 4.7,
        totalRides: 81,
        vehicle: "Ford Escape · Black",
        phoneNumber: "(204) 555-0177",
        address: "410 Main St, Winnipeg",
        distanceKm: 3.8,
        hasVehicle: true,
        isAvailable: true,
        assignedRideId: null,
    },
    {
        id: "driver-4",
        name: "Grace Thompson",
        initials: "GT",
        rating: 4.9,
        totalRides: 104,
        vehicle: "Hyundai Tucson · Grey",
        phoneNumber: "(204) 555-0166",
        address: "520 Main St, Winnipeg",
        distanceKm: 4.6,
        hasVehicle: true,
        isAvailable: false,
        assignedRideId: null,
    },
];

export const upcomingRides: Ride[] = [
    {
        id: "ride-1",
        memberId: "member-passenger-1",
        title: "Sunday Service",
        dateTime: "Sept 30, 2025 · 10:00 AM",
        pickupAddress: "123 Main St, Winnipeg",
        passengers: "2 Adults, 1 Child",
        status: "driver-response-pending",
        assignedDriverId: "driver-1",
        driverResponse: "pending",
        declinedDriverIds: [],
        driver: drivers[0],
    },
    {
        id: "ride-2",
        memberId: "member-passenger-2",
        title: "Wednesday Service",
        dateTime: "Oct 02, 2025 · 7:00 PM",
        pickupAddress: "280 Portage Ave, Winnipeg",
        passengers: "1 Adult",
        status: "confirmed",
        assignedDriverId: "driver-1",
        driverResponse: "accepted",
        declinedDriverIds: [],
        driver: drivers[0],
    },
];

export const rideHistory: Ride[] = [
    {
        id: "history-1",
        memberId: "member-passenger-3",
        title: "Sunday Service",
        dateTime: "Sept 23, 2025 · 10:00 AM",
        pickupAddress: "375 Main St, Winnipeg",
        passengers: "2 Adults",
        status: "completed",
        assignedDriverId: "driver-1",
        driverResponse: "accepted",
        declinedDriverIds: [],
        driver: drivers[0],
    },
    {
        id: "history-2",
        memberId: "member-passenger-4",
        title: "Wednesday Service",
        dateTime: "Sept 20, 2025 · 7:00 PM",
        pickupAddress: "450 Broadway, Winnipeg",
        passengers: "1 Adult, 1 Child",
        status: "completed",
        assignedDriverId: "driver-1",
        driverResponse: "accepted",
        declinedDriverIds: [],
        driver: drivers[0],
    },
    {
        id: "history-3",
        memberId: "member-passenger-5",
        title: "Sunday Service",
        dateTime: "Sept 16, 2025 · 10:00 AM",
        pickupAddress: "610 Main St, Winnipeg",
        passengers: "1 Adult",
        status: "cancelled",
        assignedDriverId: null,
        driverResponse: null,
        declinedDriverIds: [],
    },
];